### ISSUE TITLE
Break out the vSphere portion into separate module

### ISSUE THREAD

**Issue by c0dyhi11** [packet-labs/google-anthos#113]
We need to compare this repo as well as:
packet-labs/vmware-on-packet
damiens version of this repo as well.

**Comment by displague** [comment]
Once https://github.com/packet-labs/terraform-packet-vmware/pull/2 has landed, we should compare notes with this project and get this project to use that module (with any needed enhancements).

We'll need to expose variables and outputs for everything this `google-anthos` project needs from the vSphere module.

**Comment by displague** [comment]
Thanks for getting the changes needed for Anthos added to the vSphere project, @c0dyhi11.

Those changes have been released as `v2.1.0` of that module for integration with this project.
