### ISSUE TITLE
put private vars in a separate file

### ISSUE THREAD

**Issue by dfong** [packet-labs/google-anthos#115]
currently terraform.tfvars contains a mixture of private info (eg, orgid and API key), and non-private info (number of nodes, machine model).  it would be better to segregate the two types of info into separate files so that examples of non-private info can be created and shared.

**Comment by displague** [comment]
@dfong This sounds like something that can be done locally as a matter of Terraform configuration. https://www.terraform.io/docs/language/values/variables.html#variable-definitions-tfvars-files

You can put your secrets in `secrets.auto.tfvars` and keep the other configuration variables in `terraform.tfvars`.

I'm closing this, but feel free to reopen this if you think we should include documentation to this effect.
