### ISSUE TITLE
Move resource pool create from upload_ova.sh to deploy_vcva.py

### ISSUE THREAD

**Issue by paemason** [packet-labs/google-anthos#12]
We should move line 12 `govc pool.create '*/${vmware_resource_pool}'` to deploy_vcva.py for users that are not completing the Anthos prerequisites .

This is the more logical place for it any how.

We may also want to refactor upload_ova.sh to be a .py to keep consistency.

**Comment by paemason** [comment]
@boredabdel tagging you on this until we can add you as a collaborator and assign to you.

**Comment by c0dyhi11** [comment]
@paemason If someone is not deploying Anthos automatically, and we create this resource pool for them (An Anthos pre-req). Wouldn't they not know about this step in a generic VMware Env? I think keeping this behind the "Deploy Anthos" flag is best.

**Comment by paemason** [comment]
Discussed with with @c0dyhi11 and I agree. The creating the resource pool is part of the Anthos install and should be there for someone who wants to 'practice' the full anthos install experience. We're going to close this issue.
