### ISSUE TITLE
Update all Terraform code to TF12 format to remove Warnings

### ISSUE THREAD

**Issue by c0dyhi11** [packet-labs/google-anthos#14]
There are currently warnings every time you run Terraform because of TF11 vs TF12 language changes. We should update all of the TF to be TF12.

**Comment by boredabdel** [comment]
https://github.com/packet-labs/google-anthos/pull/16

Can you assign this one to me please.

Thanks

**Comment by c0dyhi11** [comment]
Done! @boredabdel

**Comment by boredabdel** [comment]
Thanks !

**Comment by c0dyhi11** [comment]
fixes #16
