### ISSUE TITLE
Implement code to clean up assigned IP blocks

### ISSUE THREAD

**Issue by paemason** [packet-labs/google-anthos#15]
Now that we have the IP block assignment fix in, we can implement code to give back the ip blocks after the esxi hosts are converted to layer to give back the IPs.

This would reduce costs ($0.04 per hour!!) and more importantly give back the IPs to be used on different projects.

I've tested manually deleting the IP blocks after the project was created and it had no impacted on the environment or on the destroy procedure.

**Comment by c0dyhi11** [comment]
I fixed this in the VMware only version of this repo.
I'll try and get this turned into a PR soon.
Here are the changes: 
https://github.com/c0dyhi11/vmware-on-packet/blob/bd368a0f70f4abb0aa65c4593580560bc85a842e/08-esx-host-networking.tf#L59
https://github.com/c0dyhi11/vmware-on-packet/blob/bd368a0f70f4abb0aa65c4593580560bc85a842e/templates/esx_host_networking.py#L153
https://github.com/c0dyhi11/vmware-on-packet/blob/bd368a0f70f4abb0aa65c4593580560bc85a842e/templates/esx_host_networking.py#L159
https://github.com/c0dyhi11/vmware-on-packet/blob/bd368a0f70f4abb0aa65c4593580560bc85a842e/templates/esx_host_networking.py#L162
https://github.com/c0dyhi11/vmware-on-packet/blob/bd368a0f70f4abb0aa65c4593580560bc85a842e/templates/esx_host_networking.py#L344
