### ISSUE TITLE
move admin workstation creation over to gkeadm

### ISSUE THREAD

**Issue by paemason** [packet-labs/google-anthos#18]
1.3 will bring a new method for bringing up the admin workstation: gkeadm. We should align with the product direction and use gkeadm instead of terraform for the admin workstation bring up moving forward.

**Comment by matthewkrupnik** [comment]
We have a need to deploy older versions to be able to test upgrades. I would really appreciate maintaining backwards compatibility at least one minor version back. So maybe until 1.4.0 is released keep a way to deploy 1.2.x.

**Comment by paemason** [comment]
Thanks for the feedback on what you'd need for your use case.

I think we can do a version check and use the terraform method for anything pre 1.3. We have something similar in place currently on the bundled load balancer. 

At a minimum, users will always be able to deploy just the vsphere components and then choose their version Anthos and how they want to deploy it, but I'd like to try to keep both methods in the code.
