### ISSUE TITLE
Using VMware vSphere 6.7 for ESXi hosts

### ISSUE THREAD

**Issue by vhamburger** [packet-labs/google-anthos#26]
Tried to modify variable "vmware_os" to use more recent 6.7 version. But that failed. 
Is there a way to use the more recent 6.7 version for the vSphere hosts? Given that 6.5 is more than 5 years old by now switchting to 6.7 would be the far better option...
Also, Anthos fully supports vSphere 6.7 as of version 1.2.0

**Comment by paemason** [comment]
Currently Packet does not support ESXi 6.7 installed on their systems. There has been discussions as to when that might happen. @c0dyhi11 any updates?

**Comment by paemason** [comment]
This is possible now using the gen 3 hardware see: https://github.com/packet-labs/google-anthos#using-packet-gen-3-hardware-and-esxi-67
