### ISSUE TITLE
Add enableha=true to load balancer config

### ISSUE THREAD

**Issue by paemason** [packet-labs/google-anthos#35]
1.3 will introduce a new field within loadbalancerconfig to enable ha aptly named enableha.

We should enable this for releases 1.3 and beyond. But if this field is in a 1.2 deployment then the config will be invalid.

Some sed-fu should be applied to make this work.

**Comment by liuyuan10** [comment]
If you are using vds v6.6, it's just as simple as running 
gkectl prepare network --config=config.yaml

to enable MAC learning for the portgroups used by lb.
