### ISSUE TITLE
Create option to use existing Packet project

### ISSUE THREAD

**Issue by paemason** [packet-labs/google-anthos#8]
@c0dyhi11 
We should create boolean/if logic to allow the choice to create a Packet Project or use an existing one.

Known limitation of using an existing project- 

- Packet Project supports max of 12 VLANs, and our build uses 5. Therefore there would be a maximum of 2 of these builds per project.

**Comment by boredabdel** [comment]
Will have a PR ready in the next couple of days!

**Comment by boredabdel** [comment]
Do you still want to close this one in favor or your pr ? i can get this out in 1 or 2 days if needed ?

**Comment by paemason** [comment]
I closed your PR because I incorporated it into in my code for ssh key. The code is already complete if you want review pr #45 and then I'll merge it.

Sorry about that, but I needed the code right away for a project.

**Comment by boredabdel** [comment]
Understood, no issues sorry for the late reply, I will pick an other issue
